import type { Metadata } from "next";
import { LegalPage, LegalSection } from "@/components/marketing/legal-page";
import { CONTACT_EMAIL } from "@/lib/site";

export const metadata: Metadata = {
  title: "Privacy Policy · LearnHub",
  description: "How LearnHub collects, uses, and protects your data. Plain English, no surprises.",
};

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy" lastUpdated="23 July 2026">
      <p>
        LearnHub (&ldquo;LearnHub&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) is an AI career coach
        for people entering tech across Africa. This policy explains what we collect, why, and the
        choices you have. We keep it short and honest.
      </p>

      <LegalSection heading="What we collect">
        <ul>
          <li>
            <strong>Your account details</strong>: your email and name. If you sign in with Google,
            we receive your name, email, and profile picture from Google.
          </li>
          <li>
            <strong>Your assessment answers</strong>: the responses you give about your background,
            interests, goals, and constraints.
          </li>
          <li>
            <strong>What we generate for you</strong>: your career recommendation, learning roadmap,
            and progress.
          </li>
          <li>
            <strong>Your messages to the AI coach</strong>: the questions you ask and the replies
            you receive.
          </li>
          <li>
            <strong>Basic usage data</strong>: needed to keep the service running securely and to
            control our AI costs while we&rsquo;re free.
          </li>
        </ul>
        <p>We do not ask for your phone number, payment details, or any government ID.</p>
      </LegalSection>

      <LegalSection heading="How we use it">
        <ul>
          <li>To create your personalized career match, roadmap, and coaching.</li>
          <li>To save your results so revisiting them never costs you data or a new AI charge.</li>
          <li>To keep your account secure and the service reliable.</li>
          <li>To understand what&rsquo;s working so we can improve the product.</li>
        </ul>
        <p>
          We <strong>do not sell your data</strong>, and we do not show you ads.
        </p>
      </LegalSection>

      <LegalSection heading="Who we share it with">
        <p>
          We use a small number of trusted providers to run LearnHub, and share only what each one
          needs:
        </p>
        <ul>
          <li>
            <strong>Supabase</strong>: securely stores your account and your saved results.
          </li>
          <li>
            <strong>Anthropic (Claude)</strong>: powers the AI. Your assessment answers and coach
            messages are sent to Anthropic&rsquo;s API to generate your recommendation, roadmap, and
            replies. Anthropic does not use this to train its models on API data.
          </li>
          <li>
            <strong>Google</strong>: only if you choose to sign in with Google.
          </li>
        </ul>
        <p>
          We may also disclose data if the law requires it. That&rsquo;s the full list. We
          don&rsquo;t share your data with anyone else.
        </p>
      </LegalSection>

      <LegalSection heading="The AI coach is AI">
        <p>
          Your coach and career recommendations are generated by artificial intelligence, not a
          human. It&rsquo;s helpful, but it can be wrong. Treat its guidance as a starting point,
          not professional career, financial, or legal advice.
        </p>
      </LegalSection>

      <LegalSection heading="How long we keep it">
        <p>
          We keep your data for as long as your account is active. If you ask us to delete your
          account, we remove your personal data, usually within 30 days, except anything we&rsquo;re
          legally required to keep.
        </p>
      </LegalSection>

      <LegalSection heading="Your choices">
        <ul>
          <li>You can view and update your details in Settings.</li>
          <li>You can ask us to delete your account and data at any time.</li>
          <li>You can stop using the service whenever you like.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="Cookies">
        <p>
          We use a small number of cookies that are necessary to keep you signed in and to keep the
          service secure. We don&rsquo;t use advertising or tracking cookies.
        </p>
      </LegalSection>

      <LegalSection heading="Analytics">
        <p>
          We count page views so we can see which parts of LearnHub are useful and which are not.
          This uses Vercel Analytics, which sets no cookies and does not follow you across other
          websites. It records the page, the country, and the kind of device — never your name, your
          email, or anything you typed.
        </p>
      </LegalSection>

      <LegalSection heading="Children">
        <p>
          LearnHub is intended for people aged 16 and over. We don&rsquo;t knowingly collect data
          from anyone younger.
        </p>
      </LegalSection>

      <LegalSection heading="Changes to this policy">
        <p>
          As LearnHub grows, we may update this policy. If we make a meaningful change, we&rsquo;ll
          update the date above and, where appropriate, let you know in the app.
        </p>
      </LegalSection>

      <LegalSection heading="Contact us">
        <p>
          Questions, or want your data deleted? Email us at{" "}
          <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
