import type { Metadata } from "next";
import { LegalPage, LegalSection } from "@/components/marketing/legal-page";
import { CONTACT_EMAIL } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms of Service · LearnHub",
  description:
    "The simple terms for using LearnHub. Free while in beta, provided honestly and as-is.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" lastUpdated="23 July 2026">
      <p>
        These terms cover your use of LearnHub (&ldquo;LearnHub&rdquo;, &ldquo;we&rdquo;,
        &ldquo;us&rdquo;). By creating an account or using the service, you agree to them. We&rsquo;ve
        kept them plain.
      </p>

      <LegalSection heading="What LearnHub is">
        <p>
          LearnHub is an AI career coach. You take a short assessment and receive an AI-generated
          career match, a learning roadmap, and access to an AI coach. It&rsquo;s designed to help
          you make decisions, not to make them for you.
        </p>
      </LegalSection>

      <LegalSection heading="It&rsquo;s free while in beta">
        <p>
          LearnHub is currently free to use. We may add paid features in the future, but we&rsquo;ll
          always be clear about what costs money before you pay for anything. Being a beta, parts of
          the service may change, break, or be unavailable at times.
        </p>
      </LegalSection>

      <LegalSection heading="The AI guidance is not professional advice">
        <p>
          Your recommendations and coaching are generated by artificial intelligence. They can be
          incomplete or wrong. LearnHub is <strong>not</strong> a substitute for professional
          career, financial, legal, or educational advice, and we don&rsquo;t guarantee any job,
          income, or outcome. Decisions you make based on LearnHub are your own.
        </p>
      </LegalSection>

      <LegalSection heading="Your account">
        <ul>
          <li>Give accurate information and keep your login secure.</li>
          <li>You&rsquo;re responsible for activity that happens under your account.</li>
          <li>Tell us promptly if you think someone else has accessed it.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="Fair use">
        <p>When using LearnHub, please don&rsquo;t:</p>
        <ul>
          <li>Break the law or use it to harm others.</li>
          <li>Try to hack, overload, scrape, or reverse-engineer the service.</li>
          <li>Resell or copy the service or its content as your own.</li>
          <li>Misuse the AI coach to generate harmful, hateful, or illegal content.</li>
        </ul>
        <p>We may suspend accounts that abuse the service.</p>
      </LegalSection>

      <LegalSection heading="Your content">
        <p>
          Your assessment answers and messages remain yours. You give us permission to process them
          so we can provide the service to you (see our{" "}
          <a href="/privacy">Privacy Policy</a>). The recommendations and roadmaps we generate are
          yours to use for your own career.
        </p>
      </LegalSection>

      <LegalSection heading="Our content">
        <p>
          The LearnHub name, logo, design, and software belong to us. Using the service doesn&rsquo;t
          give you ownership of them.
        </p>
      </LegalSection>

      <LegalSection heading="Availability and liability">
        <p>
          We work hard to keep LearnHub running, but we provide it &ldquo;as is&rdquo; without
          guarantees, and especially so during beta. To the extent the law allows, we&rsquo;re not
          liable for losses arising from your use of the service or from decisions based on its AI
          guidance.
        </p>
      </LegalSection>

      <LegalSection heading="Ending your use">
        <p>
          You can stop using LearnHub and delete your account at any time. We may suspend or end
          access if these terms are broken or if we need to for legal or security reasons.
        </p>
      </LegalSection>

      <LegalSection heading="Changes to these terms">
        <p>
          We may update these terms as LearnHub grows. If we make a meaningful change, we&rsquo;ll
          update the date above and, where appropriate, let you know in the app. Continuing to use
          LearnHub means you accept the updated terms.
        </p>
      </LegalSection>

      <LegalSection heading="Contact us">
        <p>
          Questions about these terms? Email us at{" "}
          <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
