import "server-only";
import Anthropic from "@anthropic-ai/sdk";
import { z } from "zod";
import { AI_DEMO_MODE, MODELS } from "./config";
import { DEMO_MODEL, demoDelay, demoQuiz } from "./demo";
import { extractText, parseJson } from "./parse";
import { balanceQuiz } from "@/lib/quiz/balance";

export const QUESTIONS_PER_QUIZ = 5;
export const PASS_MARK = 80;

/**
 * One multiple-choice question.
 *
 * `correct_index` is the answer key. It is stored, and it must never reach the
 * browser — see lib/quiz/sanitize.ts. Four options exactly, because a variable
 * count makes both the UI and the "one in four by guessing" maths unstable.
 *
 * `id` is generated by us rather than taken from the model: it is the key an
 * answer is stored and re-marked under, and a model that repeats or omits an id
 * would silently corrupt an attempt's record.
 */
export const QuizQuestionSchema = z.object({
  id: z.string().min(1),
  prompt: z.string().min(1),
  options: z.array(z.string().min(1)).length(4),
  correct_index: z.number().int().min(0).max(3),
  explanation: z.string().min(1),
});

export type QuizQuestion = z.infer<typeof QuizQuestionSchema>;

/** What the model returns: the same shape without the id, which we assign. */
const ModelQuestionSchema = QuizQuestionSchema.omit({ id: true });

const ModelQuizSchema = z.object({
  questions: z.array(ModelQuestionSchema).length(QUESTIONS_PER_QUIZ),
});

export const QuizSchema = z.object({
  questions: z.array(QuizQuestionSchema).length(QUESTIONS_PER_QUIZ),
});

export type QuizOutput = z.infer<typeof QuizSchema>;

const SYSTEM = `You are LearnHub AI, an expert tech career coach for Africa. Write a short quiz that checks whether someone has actually learned one step of a learning roadmap.

Write exactly ${QUESTIONS_PER_QUIZ} multiple-choice questions. Each has exactly 4 options and exactly one correct answer.

WHAT MAKES A GOOD QUESTION HERE:
Test understanding, not recall of trivia. A person who studied the step should pass; a person who only skimmed the titles should not. Ask about what the skill is for and when to use it, not about version numbers, dates, or who invented something. Prefer a small realistic situation ("You have a spreadsheet with duplicate rows. What do you do first?") over a definition.
Every wrong option must be plausible to someone who half-learned the material. Never use "all of the above", "none of the above", or a joke option: they make the answer guessable without knowing anything.
Vary which position the correct answer sits in across the ${QUESTIONS_PER_QUIZ} questions. Do not put it in the same slot every time.
The explanation says why the right answer is right, in one or two sentences, so someone who got it wrong learns something.

HOW TO WRITE (every string you return is read by the user):
Plain English, short sentences, speak directly to them ("you", "your"). Never use an em dash or en dash in prose; use a comma, a colon, or start a new sentence. En dashes are fine inside number ranges like 6–9 months. Avoid promotional filler and the words crucial, pivotal, robust, seamless, leverage, unlock, empower, transformative, testament, landscape, journey, and vibrant. Do not tack on "-ing" clauses that add no information. No emoji.

Respond with ONLY a JSON object, with no prose and no markdown code fences:
{
  "questions": [
    {
      "prompt": string,
      "options": [string, string, string, string],
      "correct_index": number,          // 0-3
      "explanation": string
    }
  ]
}`;

export async function generateQuiz(input: {
  careerTitle: string;
  stepTitle: string;
  stepDescription: string;
  skill: string;
}): Promise<{
  quiz: QuizOutput;
  usage: { input: number; output: number };
  model: string;
}> {
  // Demo mode: no API call. Sample output goes through the same Zod gate as
  // real model output, so nothing unvalidated can ever persist.
  if (AI_DEMO_MODE) {
    await demoDelay(400);
    return {
      quiz: QuizSchema.parse(withIds(demoQuiz(input.stepTitle, input.skill))),
      usage: { input: 0, output: 0 },
      model: DEMO_MODEL,
    };
  }

  const client = new Anthropic();

  const userContent = `Career: ${input.careerTitle}
Roadmap step: ${input.stepTitle}
What this step covers: ${input.stepDescription}
Core skill: ${input.skill}

Write the ${QUESTIONS_PER_QUIZ} questions for this step. Return only the JSON object.`;

  const model = MODELS.quiz;
  // The system prompt is the stable prefix across every step of every roadmap,
  // so it caches and only the short per-step content is billed at full rate.
  const res = await client.messages.create({
    model,
    max_tokens: 2000,
    system: [{ type: "text", text: SYSTEM, cache_control: { type: "ephemeral" } }],
    messages: [{ role: "user", content: userContent }],
  });

  const parsed = ModelQuizSchema.parse(parseJson(extractText(res.content)));

  return {
    quiz: QuizSchema.parse(withIds(parsed)),
    usage: { input: res.usage.input_tokens, output: res.usage.output_tokens },
    model,
  };
}

/**
 * Assign stable question ids. `q1`..`q5` scoped to the quiz, not globally
 * unique — a missed-question id is only ever interpreted alongside the step it
 * came from, and short ids keep the jsonb small.
 */
function withIds(parsed: { questions: Omit<QuizQuestion, "id">[] }): QuizOutput {
  const questions = parsed.questions.map((q, i) => ({ ...q, id: `q${i + 1}` }));
  /* Balance where the correct answer sits before storing. The SYSTEM prompt
     above asks the model to vary it, and the first 26 real quizzes came back
     with B correct 61% of the time and D correct in none of 130 questions —
     9 of the 26 were passable by tapping one letter five times. A model asked
     to be random is not random, so this is enforced in code. */
  return { questions: balanceQuiz(questions) };
}
